### PR TITLE
fixes windows composite key: #102 - add composite key

### PR DESCRIPTION
**Pull request by Archina**
[#102 - Text input yields Key::Unknown on windows_term using alt](https://github.com/mitsuhiko/console/issues/102)

### CODE REVIEW

**Review by pksunkara — APPROVED** [review]

**Comment by pksunkara** [comment]
Okay, what is a composite key and how is it related to macos and ubuntu?

**Comment by Archina** [comment]
As stated in the linked issue, the composite key does not really exist. It also does not relate to linux. The mapping is more for the Alt key - however, calling it Key::Alt seemed misleading as the mapping within winapi seems to be incorrect as well (it points to the Menu key instead).

The issue is that the windows term generates Key::Unknown + Key::Char events when using this technique. (You should be able to reproduce this by using altGr + / to create a ¿ character). This causes dialoguer to crash.

**Comment by pksunkara** [comment]
If you check https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes, VK_MENU **is** ALT key. So, instead of composite, let's put `Key::Alt`

**Comment by Archina** [comment]
Then I misunderstood that. I will use Key::Alt then instead. Thank you very much!

**Review by pksunkara — APPROVED** [review]

**Pull request merged**
