### PR TITLE
read only one byte in read_single_key unless we find an escape sequence

### PR DESCRIPTION
**Pull request by rjwalters**
When input is pasted into a unix terminal and collected using `read_single_key` I noticed that only every 20th character was available. I don't think it should be necessary to read more than one byte at a time. (Hopefully no unicode issues etc.)

### CODE REVIEW

**Comment by rjwalters** [comment]
This causes problems for keystrokes that are longer than one byte... for example in dialoguer's Select functionality. I think we need to look for multibyte keystrokes and read more of the buffer when we find them...

``` rust
b"\x1b[D" => Key::ArrowLeft,
b"\x1b[C" => Key::ArrowRight,
b"\x1b[A" => Key::ArrowUp,
b"\x1b[B" => Key::ArrowDown,
b"\n" | b"\r" => Key::Enter,
b"\x1b" => Key::Escape,
b"\x7f" => Key::Backspace,
b"\x1b[H" => Key::Home,
b"\x1b[F" => Key::End,
b"\t" => Key::Tab,
b"\x1b[3~" => Key::Del,
```

**Comment by pksunkara** [comment]
Sounds good, but how does utf8 work with this?

**Comment by rjwalters** [comment]
> Sounds good, but how does utf8 work with this?

I'm not sure I understand the intent of `get_single_key()` -- it looks like it could be pretty complicated to properly support all of the [escape sequences](https://github.com/bminor/bash/blob/master/lib/sh/strtrans.c). Is it enough to make sure we manage the full set in `pub enum Key`?

We can detect UTF-8 byte sequences and manage these as another special case if that's in scope - does `termios` support UTF-8 input?

It would be nice to have some tests for this sort of thing if there is a way to mock input in termios.

**Comment by rjwalters** [comment]
I added special cases to capture UTF-8 based on https://en.wikipedia.org/wiki/UTF-8

**Comment by pksunkara** [comment]
Thanks. This is great work. Really appreciate it. Feel free to open PRs anytime you want. I will always respond fast. 😄

**Pull request merged**
