### PR TITLE
feat: unix term add Control-A (home), Control-E (end) and Control-H support

### PR DESCRIPTION
**Pull request by ttys3**
feat: unix term add Control-A (home), Control-E (end) and Control-H (8) support

ref to https://github.com/prompt-toolkit/python-prompt-toolkit/blob/0ae9aa688e0b3f81a29a33015ca1f8a9adb05c6c/prompt_toolkit/input/ansi_escape_sequences.py#L26

### CODE REVIEW

**Comment by pksunkara** [comment]
Aren't they already supported https://github.com/mitsuhiko/console/blob/cc3fcc154a993501222b0ddf527d5f055d0329b7/src/unix_term.rs#L160-L162?

**Review by pksunkara — CHANGES_REQUESTED** [review]
Commented

**Comment by ttys3** [comment]
@pksunkara  no,  `^[[H` is not `^A`,  `^[[F` is also not `^E`, the same doese Control-H

I tested this once again.

in the other way, if it is the same, the python `prompt_toolkit` lib would not impiment it twice ? isn't it?

**Comment by ttys3** [comment]
and, use Control-A (home), Control-E (end) and Control-H will keep your hands in the main keyboard area, without move to the right far away

**Review by pksunkara — APPROVED** [review]

**Pull request merged**
