### PR TITLE
Add support to move cursor to (x, y) position

### PR DESCRIPTION
**Pull request by Roger**
This also adds an example of how use it.
Didn't test windows support(don't have a windows machine).

### CODE REVIEW

**Comment by Revertron** [comment]
It would be great to merge this one.

**Comment by mitsuhiko** [comment]
I would like to merge this but this would need msys support still.

**Comment by Roger** [comment]
This supports windows, but didn't have any windows machine to test, I guess that I can try in a vm

**Comment by Roger** [comment]
I updated the PR to support msys and tested using msys2 and also cmd.exe on a vm and works fine

**Comment by mitsuhiko** [comment]
Thanks!

**Pull request merged**
